class asignacion_exception(Exception):
    pass